_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL/BMF/
    split: train
    subset_labels: [109, 110, 111, 112, 113, 114, 115, 116, 117, 118]
    # [109, 110, 111, 112, 113, 114, 115, 116, 117, 118]
    # [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
    # subset_file: /data/datasets/CIL/cub/cub/all/session_2.txt
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 119
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 119
    transform: test