_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL/BMF/
    split: train
    subset_labels: [149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168]
    # [179, 180, 181, 182, 183, 184, 185, 186, 187, 188]
    # [169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188]
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 169
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 169
    transform: test