_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL/BM200/CIL/
    split: train
    subset_labels: 180
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL/BM200/CIL/
    split: test
    subset_labels: 180
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL/BM200/CIL/
    split: test
    subset_labels: 180
    transform: test