exp_name: "'@{dataset.name}'_'@{pipeline.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_'@{mark}'/s'@{seed}'"
output_dir: ./results_0521/
save_output: True
merge_option: default
mark: default
seed: 0

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

dataset:
  name: remote

preprocessor:
  name: base

network:
  pretrained: False
  checkpoint: None

pipeline:
  name: savc_att_base

trainer:
  name: savc_att

loss:
  cls_loss: ce
  att_loss: bce
  trade_weight: 5.0
  
evaluator:
  name: savc_attr

optimizer:
  name: sgd
  num_epochs: 100
  new_epochs: 5
  lr: 0.002
  lr_base: 0.002
  lr_new: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  schedule: Step
  step: 40
  gamma: 0.1
  milestones: [60, 70]

recorder:
  name: attr
  save_scores: False
  save_csv: True
  save_all_models: False

discoverer:
  name: savc_att_discoverer
  ood_method: mls
  ood_type: attribute # classification
  val_ratio: 0.5

quantizer:
  apply: True
  name: adaround
  quant:
    default:
      weight:
        n_bits: 5
        symmetric: True
        signed: True
        granularity: channel
        range:
          name: mse
          maxshrink: 0.8
          grid: 100
        adaround:
          apply: True
      activation:
        n_bits: 32
        range:
          name: minmax
      bn_folding: True
      bias_correct: 
          momentum: 0.1
  optimizer: 
      name: adam
      lr: 0.001
  train: 
      max_epoch: 10

