_base_: [
  "configs/incremental/alice.yaml", 
  "configs/network/alice.yaml",
]

trainer:
  type: IncTrainer
  sess_cfg:
    s0:
      _base_: configs/dataloader/remote/s0.yaml
      trainer:
        max_epochs: 60
    s1:
      _base_: configs/dataloader/remote/s1.yaml
      trainer:
        max_epochs: 1

algorithm:
  type: alice

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: Constant

discover:
  val_ratio: 1.0
  ood_type: MLS
  precision_bar: 0.42
  sift_threshold: 0.65

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/inc_remote_alice
output_dir: ./output/supervised/inc_remote_alice
