_base_: [
  "configs/incremental/savc.yaml",
  "configs/network/fact.yaml",
]

trainer:
  type: IncTrainer
  sess_cfg:
    s0:
      _base_: configs/dataloader/remote/s0.yaml
      trainer:
        max_epochs: 70
    s1:
      _base_: configs/dataloader/remote/s1.yaml
      trainer:
        max_epochs: 1
  ncd_cfg:
    metrics: [msp]
    tpr_th: 0.95
    pred_th: 0.42
    dataloader:
      batch_size: 64
      num_workers: 8
      shuffle: False
      pin_memory: True

algorithm:
  type: fact

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.002
  weight_decay: 0.0001

scheduler:
  type: Constant

discover:
  val_ratio: 1.0
  ood_type: MLS
  precision_bar: 0.42
  sift_threshold: 0.65

seed: 0
device: cuda

ood_type: MLS
exp_name: exp
work_dir: ./output/supervised/inc_remote_savc
