_base_: [
  "configs/dataloader/remote.yaml", 
  "configs/incremental/alice.yaml", 
  "configs/network/alice.yaml"
]

algorithm:
  type: alice

num_session: 2

max_epochs: 60
inc_epochs: 1

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: Constant

discover:
  val_ratio: 1.0
  ood_type: MLS
  precision_bar: 0.42
  sift_threshold: 0.65

seed: 0

num_session: 2

device: cuda

exp_name: exp
work_dir: ./output/supervised/sl_remote_alice
output_dir: ./output/supervised/sl_remote_alice