_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/BMF-1/BMF-1/
    split: train
    subset_labels: [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/BMF-1/BMF-1/
    split: test
    subset_labels: 39
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/BMF-1/BMF-1/
    split: test
    subset_labels: 39
    transform: test