_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: train
    subset_labels: [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 56
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 56
    transform: test