_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: train
    subset_labels: [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103]
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 104
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 104
    transform: test