_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: train
    subset_labels: [104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128]
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 129
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 129
    transform: test