_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/BMF-1/BMF-1/
    split: train
    subset_labels: [129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139]
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/BMF-1/BMF-1/
    split: test
    subset_labels: 140
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/BMF-1/BMF-1/
    split: test
    subset_labels: 140
    transform: test