_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/BMF-1/BMF-1/
    split: train
    subset_labels: 169
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/BMF-1/BMF-1/
    split: test
    subset_labels: 169
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/BMF-1/BMF-1/
    split: test
    subset_labels: 169
    transform: test