_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: train
    subset_labels: [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165]
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 166
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 166
    transform: test