_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: train
    subset_labels: [166, 167, 168, 169, 170, 171, 172, 173, 174, 175]
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 176
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BMF
    root: /data/datasets/CIL/BMF/
    split: test
    subset_labels: 176
    transform: test