_base_: [
  configs/dataloader/OES/oesfull.yaml,
  configs/algorithms/ood_detection/dml.yaml,
]

trainer:
  type: DetTrainer
  max_epochs: 0

algorithm:
  type: VIM
  dim: 256

model:
  type: ResNet_Base
  network:
    type: ResNet50
    num_classes: 94
  checkpoint: ./output/ood/det_oes_rn50_msp_lr0.02/exp/latest.pth


criterion:
  type: CrossEntropyLoss

optimizer:
  type: SGD
  lr: 0.01
  weight_decay: 0.0001

scheduler:
  type: cosine
  T_max: 100  

seed: 0
device: cuda
CIL: False

exp_name: exp
work_dir: ./output/ood/test_vim/
