_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL_new/
    split: train
    subset_labels: 29
    # subset_file: /data/datasets/CIL_new/cub/all/session_2.txt
    transform: train

valloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL_new/
    split: test
    subset_labels: 29
    transform: test

testloader:
  dataset:
    _replace_: True
    type: BM200
    root: /data/datasets/CIL_new/
    split: test
    subset_labels: 29
    transform: test