_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: remote
    root: /new_data/dx450/ATR-13-pingzhuang/0718_dy/
    split: train
    subset_labels: 11
    transform: train

valloader:
  dataset:
    _replace_: True
    type: remote
    root: /new_data/dx450/ATR-13-pingzhuang/0718_dy/
    split: test
    subset_labels: 11
    transform: test

testloader:
  dataset:
    _replace_: True
    type: remote
    root: /new_data/dx450/ATR-13-pingzhuang/0718_dy/
    split: test
    subset_labels: 11
    transform: test
