_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/food-101/
    split: train
    subset_labels: 11
    transform: train

valloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/food-101/
    split: test
    subset_labels: 11
    transform: test

testloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/food-101/
    split: test
    subset_labels: 11
    transform: test
