_base_: configs/dataloader/_loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/0718
    split: train
    subset_labels: 11
    transform: train

valloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/0718
    split: test
    subset_labels: 11
    transform: test

testloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/0718
    split: test
    subset_labels: 11
    transform: test
