_base_: configs/dataloader/_loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/0718
    split: train
    subset_file: /data/datasets/CIL/0718/index/remote/session_1.txt
    transform: train

valloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/0718
    split: test
    subset_labels: 14
    transform: test

testloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/0718
    split: test
    subset_labels: 14
    transform: test
