_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: remote
    root: /new_data/dx450/ATR-13-pingzhuang/0718_dy/
    split: train
    subset_file: /new_data/dx450/ATR-13-pingzhuang/0718_dy/session_2.txt
    transform: train

valloader:
  dataset:
    _replace_: True
    type: remote
    root: /new_data/dx450/ATR-13-pingzhuang/0718_dy/
    split: test
    subset_labels: 14
    transform: test

testloader:
  dataset:
    _replace_: True
    type: remote
    root: /new_data/dx450/ATR-13-pingzhuang/0718_dy/
    split: test
    subset_labels: 14
    transform: test
