CIL:
  name: alice_save
  moco_dim: 128
  moco_k: 65536
  moco_m: 0.999
  moco_t: 0.07
  mlp: False
  temperature: 16
  num_crops: [2, 4]
  size_crops: [224, 96]
  min_scale_crops: [0.14, 0.05]
  max_scale_crops: [1, 0.14]
  constrained_cropping: False
  auto_augment: []
  fantasy: rotation2
  alpha: 1.0
  beta: 0.0
  base_mode: ft_cos
  new_mode: avg_cos
  incft: True
  not_data_init: False
  base_classes: 109
  num_classes: 189
  way: 10
  shot: 1
  sessions: 9