_base_: [
  configs/algorithms/incremental/fetril.yaml,
  configs/models/fetril.yaml,
]

trainer:
  type: IncTrainer
  sess_cfg:
    s0:
      _base_: configs/dataloader/BMF/s0.yaml
      trainer:
        max_epochs: 1
    s1:
      _base_: configs/dataloader/BMF/s1.yaml
      trainer:
        max_epochs: 1
    s2:
      _base_: configs/dataloader/BMF/s2.yaml
      trainer:
        max_epochs: 60
    s3:
      _base_: configs/dataloader/BMF/s3.yaml
      trainer:
        max_epochs: 60
    s4:
      _base_: configs/dataloader/BMF/s4.yaml
      trainer:
        max_epochs: 60
    s5:
      _base_: configs/dataloader/BMF/s5.yaml
      trainer:
        max_epochs: 60
    s6:
      _base_: configs/dataloader/BMF/s6.yaml
      trainer:
        max_epochs: 60
    s7:
      _base_: configs/dataloader/BMF/s7.yaml
      trainer:
        max_epochs: 60
    s8:
      _base_: configs/dataloader/BMF/s8.yaml
      trainer:
        max_epochs: 60
    s9:
      _base_: configs/dataloader/BMF/s9.yaml
      trainer:
        max_epochs: 60

algorithm:
  type: fetril

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.01
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/inc_remote_fetril_new