_base_: [
  configs/algorithms/incremental/lwf.yaml,
  configs/models/lwf.yaml,
]

trainer:
  type: IncTrainer
  sess_cfg:
    s0:
      _base_: configs/dataloader/cub200/s0.yaml
      trainer:
        max_epochs: 60
    s1:
      _base_: configs/dataloader/cub200/s1.yaml
      trainer:
        max_epochs: 60
    s2:
      _base_: configs/dataloader/cub200/s2.yaml
      trainer:
        max_epochs: 60
    s3:
      _base_: configs/dataloader/cub200/s3.yaml
      trainer:
        max_epochs: 60
    s4:
      _base_: configs/dataloader/cub200/s4.yaml
      trainer:
        max_epochs: 60
    s5:
      _base_: configs/dataloader/cub200/s5.yaml
      trainer:
        max_epochs: 60
    s6:
      _base_: configs/dataloader/cub200/s6.yaml
      trainer:
        max_epochs: 60
    s7:
      _base_: configs/dataloader/cub200/s7.yaml
      trainer:
        max_epochs: 60
    s8:
      _base_: configs/dataloader/cub200/s8.yaml
      trainer:
        max_epochs: 60
    s9:
      _base_: configs/dataloader/cub200/s9.yaml
      trainer:
        max_epochs: 60

algorithm:
  type: lwf

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.01
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/inc_cub_lwf
