_base_: [
  configs/algorithms/incremental/fact.yaml,
  configs/models/fact.yaml,
]

CIL:
  base_classes: 12
  num_classes: 15

model:
  type: FACTNET
  network:
    type: pair_resnet18
    weights: True
    fusion_pos: block1
    fusion_type: max
  base_classes: 90
  num_classes: 101

trainer:
  type: IncTrainer
  sess_cfg:
    s0:
      _base_: configs/dataloader/remoteiv/s0.yaml
      trainer:
        max_epochs: 1
    s1:
      _base_: configs/dataloader/remoteiv/s1.yaml
      trainer:
        max_epochs: 1

algorithm:
  type: fact

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.002
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/inc/inc_remote_savc
