_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: imagenetr
    root: /data/datasets/CIL/imagenet-r/
    split: train
    subset_labels: 200
    transform: train

valloader:
  dataset:
    _replace_: True
    type: imagenetr
    root: /data/datasets/CIL/imagenet-r/
    split: test
    subset_labels: 200
    transform: test

testloader:
  dataset:
    _replace_: True
    type: imagenetr
    root: /data/datasets/CIL/imagenet-r/
    split: test
    subset_labels: 200
    transform: test