_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: cub200
    root: /data/datasets/CIL/cub/
    split: train
    subset_labels: 80
    transform: train

valloader:
  dataset:
    _replace_: True
    type: cub200
    root: /data/datasets/CIL/cub/
    split: test
    subset_labels: 80
    transform: test

testloader:
  dataset:
    _replace_: True
    type: cub200
    root: /data/datasets/CIL/cub/
    split: test
    subset_labels: 80
    transform: test