_base_: configs/dataloader/OES/oesfull.yaml

trainer:
  type: DetTrainer
  gather_train_stats: False
  gather_test_stats: False
  max_epochs: 0
  load_from: './output/supervised/sl_oes_sct-b16/exp/latest.pth'


algorithm:
  type: GLMCM
  hyperparameters:
    T: 100
    factor: 1

model:
  type: LoCoOp
  backbone: 'ViT-B/16'
  local_path: ""
  dataset: 'oes'
  N_CTX: 16
  CTX_INIT: False
  image_size: 224
  CSC: True
  CLASS_TOKEN_POSITION: 'end'
  
criterion:
  type: LoCoOpLoss

optimizer:
  type: sgd
  lr: 0.01
  # type: Adam
  # lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ood/det_oes_sct-b16_glmcm
