_base_: configs/dataloader/OES/oesfull.yaml

trainer:
  type: DetTrainer
  gather_train_stats: False
  gather_test_stats: False
  max_epochs: 0

algorithm:
  type: MLS

model:
  type: CustomCLIP_ZeroShot
  num_classes: 94
  backbone: 'ViT-B/16'
  local_path: ""
  dataset: 'oes'
  text_prompt: 'simple'

criterion:
  type: CrossEntropyLoss

optimizer:
  type: Adam
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ood/det_oes_clip-b16_mls
