_base_: [
  configs/dataloader/cifar10.yaml,
  configs/algorithms/ood_detection/dml.yaml,
]

trainer:
  type: DetTrainer
  max_epochs: 0

algorithm:
  type: DML

model:
  type: DMLNet
  network:
    type: ResNet18
    num_classes: 10
  loss: dml
  checkpoint_C: output/ood/det_cifar10_rn18_dml_cosine/exp/latest.pth 
  checkpoint_N: output/ood/det_cifar10_rn18_dml_norm/exp/latest.pth

criterion:
  type: CrossEntropyLoss

optimizer:
  type: Adam
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ood/det_cifar10_rn18_dml
