_base_: configs/dataloader/cifar10.yaml

trainer:
  type: DetTrainer
  max_epochs: 1

algorithm:
  type: DML

model:
  type: DMLNet
  network:
    type: ResNet18
    num_classes: 10
  loss: center

criterion:
  # FocalLoss CenterLoss CrossEntropyLoss
  type: CenterLoss
  device: cuda
  num_classes: 10
  feat_dim: 512
# resnet18 -> 512
# resnet50 -> 2048

optimizer:
  type: Adam
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ood/det_cifar10_rn18_dml_norm
