_base_: configs/dataloader/OES/oes.yaml

trainer:
  type: DetTrainer
  gather_train_stats: False
  gather_test_stats: False
  max_epochs: 0
  load_from: './output/supervised/sl_oes_sct_b16/exp/latest.pth'


algorithm:
  type: MLS

model:
  type: LoCoOp
  backbone: 'ViT-B/16'
  dataset: 'oes_rgb_id'
  N_CTX: 16
  CTX_INIT: False
  image_size: 224
  CSC: True
  CLASS_TOKEN_POSITION: 'end'
  
criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.01
  # type: Adam
  # lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ood/ood_oes_coop_b16_mls
