from .savc import SAVC
from .fact import FACT
from .alice import Alice
from .alice_save import Alice_save
from .lwf import LwF
from .ewc import EWC
from .wa import WA
from .finetune import Finetune
from .icarl import iCaRL
from .bic import BiC
from .joint import Joint
from .coil import COIL
from .ssre import SSRE
from .fetril import FeTrIL
from .der import DER
from .memo import MEMO
from .gem import GEM