_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: food101
    root: /data/datasets/CIL/food-101/
    split: train
    subset_labels: 90
    transform: train

valloader:
  dataset:
    _replace_: True
    type: food101
    root: /data/datasets/CIL/food-101/
    split: test
    subset_labels: 90
    transform: test

testloader:
  dataset:
    _replace_: True
    type: food101
    root: /data/datasets/CIL/food-101/
    split: test
    subset_labels: 90
    transform: test
