_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/caltech101/caltech-101/
    split: train
    transform: train

valloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/caltech101/caltech-101/
    split: test
    transform: test

testloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/caltech101/caltech-101/
    split: test
    transform: test
