_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    type: CIFAR100
    root: /data/hdd/datasets/cifar100/
    train: True
    download: True
    transform:
      random_crop:
        size: 32
        padding: 4
      random_horizontal_flip:
        p: 0.5
      to_tensor: null
      normalize:
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]

valloader:
  dataset:
    type: CIFAR100
    root: /data/hdd/datasets/cifar100/
    train: False
    download: True
    transform:
      to_tensor: null
      normalize:
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]

testloader:
  dataset:
    type: CIFAR100
    root: /data/hdd/datasets/cifar100/
    train: False
    download: True
    transform:
      to_tensor: null
      normalize:
        mean: [0.5071, 0.4867, 0.4408]
        std: [0.2675, 0.2565, 0.2761]
