trainloader:
  dataset:
    type: CIFAR100
    root: /data/hdd/datasets/cifar100/
    train: True
    download: True
  batch_size: 128
  num_workers: 4
  shuffle: True

valloader:
  dataset:
    type: CIFAR100
    root: /data/hdd/datasets/cifar100/
    train: False
    download: True
  batch_size: 128
  num_workers: 4
  shuffle: False

testloader:
  dataset:
    type: CIFAR100
    root: /data/hdd/datasets/cifar100/
    train: False
    download: True
  batch_size: 128
  num_workers: 4
  shuffle: False
