_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    type: CIFAR10
    root: /new_data/dataset/cifar10/
    train: True
    download: True
    transform:
      random_crop:
        size: 32
        padding: 4
      random_horizontal_flip:
        p: 0.5
      to_tensor: null
      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]

valloader:
  dataset:
    type: CIFAR10
    root: /new_data/dataset/cifar10/
    train: False
    download: True
    transform:
      to_tensor: null
      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]

testloader:
  dataset:
    type: CIFAR10
    root: /new_data/dataset/cifar10/
    train: False
    download: True
    transform:
      to_tensor: null
      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]

# it's ood dataset loader, here i set it to the same as testloader
evalloader:
  batch_size: 64
  num_workers: 4
  dataset:
    type: CIFAR10
    root: /new_data/dataset/cifar10/
    train: False
    download: True
    transform:
      to_tensor: null
      normalize:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
