_base_: configs/dataloader/_loader.yaml

trainloader:
  dataset:
    type: ImageNet
    root: /data/hdd/datasets/ImageNet/
    split: train
    transform:
      random_resized_crop:
        size: 224
      random_horizontal_flip:
        p: 0.5
      to_tensor: null
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

valloader:
  dataset:
    type: ImageNet
    root: /data/hdd/datasets/ImageNet/
    split: val
    transform:
      resize:
        size: 256
      center_crop:
        size: 224
      to_tensor: null
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]

testloader:
  dataset:
    type: ImageNet
    root: /data/hdd/datasets/ImageNet/
    split: val
    transform:
      resize:
        size: 256
      center_crop:
        size: 224
      to_tensor: null
      normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
