dataloader:
  name: remote_dataloader
  dataset: remote
  base_class: 11
  num_classes: 14
  att_classes: 86
  way: 3
  shot: 50
  sessions: 2
  num_crops: [2, 4]
  size_crops: [224, 96]
  min_scale_crops: [0.14, 0.05]
  max_scale_crops: [1, 0.14]
  constrained_cropping: False
  auto_augment: []
  fantasy: rotation2
  txt_path: /data/datasets/CIL/0718/index/
  att_path: /new_data/dx450/Project/zzh_ood/NCD_Attr_zzh/data/Benckmark/attribute.xlsx
  split_file_train: /data/datasets/CIL/0718/train_0718/
  split_file_test: /data/datasets/CIL/0718/test_0718/  # _cheat
  batch_size_base: 64
  batch_size_new: 64
  test_batch_size: 100
  num_workers: 4
