_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/remote/0718_dy/
    split: train
    transform: train

valloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/remote/0718_dy/
    split: test
    transform: test

testloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/remote/0718_dy/
    split: test
    transform: test
