_base_: configs/dataloader/caltech101.yaml

trainer:
  type: PreTrainer
  max_epochs: 1

algorithm:
  type: StandardSL

model:
  type: ResNet18

criterion:
  type: CrossEntropyLoss

optimizer:
  type: Adam
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/sl_caltech101_rn18
