_base_: configs/dataloader/cifar10.yaml

trainer:
  type: PreTrainer
  max_epochs: 10

algorithm:
  type: DML_Cosine

model:
  type: ResNet18

criterion:
  type: CrossEntropyLoss

optimizer:
  type: Adam
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/sl_cifar10_rn18
