_base_: configs/dataloader/OES/oesfull.yaml

trainer:
  type: PreTrainer
  max_epochs: 20

algorithm:
  type: StandardSL

model:
  type: CoOp
  backbone: 'ViT-B/16'
  local_path: ""
  dataset: 'oes'
  N_CTX: 16
  CTX_INIT: False
  image_size: 224
  CSC: True
  CLASS_TOKEN_POSITION: 'end'
  

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.01
  weight_decay: 0.0005

scheduler:
  type: cosine_warmup
  T_max: 20
  warmup_epochs: 1
  warmup_type: constant
  warmup_lr: 1e-4

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/sl_oes_coop-b16
