_base_: configs/dataloader/OES/oes.yaml

trainer:
  type: PreTrainer
  max_epochs: 20
  # load_from: './output/supervised/sl_oes_coop_b16/exp/latest.pth'

algorithm:
  type: StandardSL

model:
  type: DPM
  backbone: 'ViT-B/16'
  dataset: 'oes_rgb_id'
  N_CTX: 16
  CTX_INIT: False
  image_size: 224
  CSC: True
  CLASS_TOKEN_POSITION: 'end'
  

criterion:
  type: DPMLoss

optimizer:
  type: sgd
  lr: 0.01
  # type: Adam
  # lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant
  # type: cosine

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/sl_oes_dpm_b16
