_base_: configs/dataloader/OES/oes.yaml

trainer:
  type: PreTrainer
  max_epochs: 1

algorithm:
  type: StandardSL

model:
  type: MobileNet_Base   # or mobilenet_v3_large
  network:
    type: mobilenet_v3_small   # 或 mobilenet_v3_large
    num_classes: 94

criterion:
  type: CrossEntropyLoss

optimizer:
  type: Adam
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/sl_oes_mnv3
