_base_: configs/dataloader/remoteiv.yaml

trainer:
  type: PreTrainer
  max_epochs: &Epoch 10

algorithm:
  type: StandardSL

model:
  type: Pair_ResNet18
  weights: True
  num_classes: 15
  fusion_pos: SoftMax 
  fusion_type: add

criterion:
  type: CrossEntropyLoss

optimizer:
  type: Adam
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: Cosine
  T_max: *Epoch
  eta_min: 1e-6

seed: 0
device: cuda

exp_name: ext
work_dir: ./output/supervised/sl_remoteiv_prn18
