_base_: [
  configs/algorithms/incremental/savc.yaml,
  configs/models/savc.yaml,
]

trainer:
  type: Inference
  sess_cfg:
    s0:
      _base_: configs/dataloader/remote/s0.yaml
      trainer:
        max_epochs: 0
    s1:
      _base_: configs/dataloader/remote/s1.yaml
      trainer:
        max_epochs: 0
  ncd_cfg:
    metrics: [ attr ]
    tpr_th: 0.95
    prec_th: 0.3

algorithm:
  type: savc

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/ncdia_remote_savc
model_detect: runs/detect/remote/weights_xz/best.pt
inference_data: [/data/datasets/remote/pipeline/remote_k/images/val/,
                 /data/datasets/remote/pipeline/remote_uk/images/]
inference_ann: [/data/datasets/remote/pipeline/remote_k/labels_xml/val/,
                /data/datasets/remote/pipeline/remote_uk/labels_xml/]
ckpt: [/data/datasets/remote/pipeline/exp/savc/task_0.pth,
       /data/datasets/remote/pipeline/exp/savc/task_1.pth]
confidence: 0.5

threshold: 0.995
