model:
  type: BEEFISONet
  network:
    type: resnet18
    pretrained: True
  base_classes: 9
  num_classes: 189
  net_alice:
    moco_dim: 128
    moco_k: 65536
    moco_m: 0.999
    moco_t: 0.07
    mlp: False
    temperature: 16
    not_data_init: False
    num_crops: [2, 4]
    size_crops: [224, 96]
    min_scale_crops: [0.14, 0.05]
    max_scale_crops: [1, 0.14]
    constrained_cropping: False
    auto_augment: []
    fantasy: rotation2
    alpha: 1.0
    beta: 0.0
    base_mode: ft_cos
    new_mode: avg_cos
    incft: True