model:
  type: DMLNet
  network_C:
    type: resnet18
    num_classes: 10
  network_N:
    type: resnet18
    num_classes: 10
  # pretrained: True
  checkpoint_C: output/supervised/sl_cifar10_rn18_DML_Cosine/exp/latest.pth 
  checkpoint_N: output/supervised/sl_cifar10_rn18_DML_Norm/exp/latest.pth
