model:
  type: AliceNET
  network:
    type: resnet18
    pretrained: True
  base_classes: 20
  num_classes: 200
  att_classes: 86
  # pretrained: True
  # checkpoint: /new_data/dx450/Project/zzh_ood/NCD_Attr/results/remote_resnet18_savc_att_q_savc_att_e15_lr0.002_default/s0/best_epoch15_acc0.9920.ckpt   # ignore if pretrained is false
  net_alice:
    moco_dim: 128
    moco_k: 65536
    moco_m: 0.999
    moco_t: 0.07
    mlp: False
    temperature: 16
    not_data_init: False
    num_crops: [2, 4]
    size_crops: [224, 96]
    min_scale_crops: [0.14, 0.05]
    max_scale_crops: [1, 0.14]
    constrained_cropping: False
    auto_augment: []
    fantasy: rotation2
    alpha: 1.0
    beta: 0.0
    base_mode: ft_cos
    new_mode: avg_cos
    incft: True