_base_: [
  configs/dataloader/OES/oesfull.yaml,
]

trainer:
  type: DetTrainer
  max_epochs: 1
  gather_train_stats: False
  gather_test_stats: True

algorithm:
  type: DML

model:
  type: DMLNet
  network:
    type: ResNet18
    num_classes: 94
  loss: center

criterion:
  # FocalLoss CenterLoss CrossEntropyLoss
  type: CenterLoss
  device: cuda
  num_classes: 94
  feat_dim: 512
# resnet18 -> 512
# resnet50 -> 2048

optimizer:
  type: Adam
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda
CIL: False

exp_name: train
work_dir: ./output/ood/det_oes_rn18_dml_norm
