_base_: [
  configs/dataloader/OES/oesfull.yaml,
]

trainer:
  type: DetTrainer
  max_epochs: 1
  gather_train_stats: False
  gather_test_stats: True

algorithm:
  type: DML

model:
  type: DMLNet
  network:
    type: ResNet18
    num_classes: 94
  # focal center dml
  loss: focal

criterion:
  type: FocalLoss

optimizer:
  type: Adam
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda
CIL: False

exp_name: train
work_dir: ./output/ood/det_oes_rn18_dml_cosine
