_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: OES
    # root: /data/datasets/CIL/BMF/
    root: /new_data/datasets/Benchmark/CIL
    split: train
    subset_labels: [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108]
    transform: train

valloader:
  dataset:
    _replace_: True
    type: OES
    # root: /data/datasets/CIL/BMF/
    root: /new_data/datasets/Benchmark/CIL
    split: test
    subset_labels: 109
    transform: test

testloader:
  dataset:
    _replace_: True
    type: OES
    # root: /data/datasets/CIL/BMF/
    root: /new_data/datasets/Benchmark/CIL
    split: test
    subset_labels: 109
    transform: test