_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: remoteiv
    root_a: /data/gjq/Dataset/VAIS/Fine_paired/vis
    root_b: /data/gjq/Dataset/VAIS/Fine_paired/ir
    split: train
    subset_file: /data/gjq/Dataset/VAIS/Fine_paired/session_1.txt
    transform: train

valloader:
  dataset:
    _replace_: True
    type: remoteiv
    root_a: /data/gjq/Dataset/VAIS/Fine_paired/vis
    root_b: /data/gjq/Dataset/VAIS/Fine_paired/ir
    split: test
    subset_labels: 15
    transform: test

testloader:
  dataset:
    _replace_: True
    type: remoteiv
    root_a: /data/gjq/Dataset/VAIS/Fine_paired/vis
    root_b: /data/gjq/Dataset/VAIS/Fine_paired/ir
    split: test
    subset_labels: 15
    transform: test
