_base_: [
  configs/algorithms/incremental/alice_save.yaml,
  configs/models/alice.yaml,
]

trainer:
  type: IncTrainer
  sess_cfg:
    s0:
      _base_: configs/dataloader/remote/s0.yaml
      trainer:
        max_epochs: 70
    s1:
      _base_: configs/dataloader/remote/s1.yaml
      trainer:
        max_epochs: 1
  ncd_cfg:
    metrics: [msp]
    tpr_th: 0.95
    prec_th: 0.3

algorithm:
  type: alice_save

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/supervised/ncdia_remote_alice
