_base_: [
  configs/algorithms/incremental/savc.yaml,
  configs/models/savc.yaml,
]

trainer:
  type: IncTrainer
  sess_cfg:
    s0:
      _base_: configs/dataloader/remote/s0.yaml
      trainer:
        max_epochs: 70
    s1:
      _base_: configs/dataloader/remote/s1.yaml
      trainer:
        max_epochs: 1
  ncd_cfg:
    metrics: [mcm]
    tpr_th: 0.65
    prec_th: 0.1

algorithm:
  type: savc

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
# work_dir: ./output/supervised/ncdia_remote_savc_xz
work_dir: ./output/supervised/ncdia_remote_savc_1
