_base_: [
  configs/algorithms/incremental/alice.yaml,
  configs/models/alice.yaml,
]

CIL:
  base_classes: &base_classes 12
  num_classes: &num_classes 15

model:
  type: AliceNET
  network:
    type: pair_resnet18
    weights: True
    fusion_pos: block1
    fusion_type: max
  base_classes: *base_classes
  num_classes: *num_classes

trainer:
  type: IncTrainer
  sess_cfg:
    s0:
      _base_: configs/dataloader/remoteiv/s0.yaml
      trainer:
        max_epochs: 1
    s1:
      _base_: configs/dataloader/remoteiv/s1.yaml
      trainer:
        max_epochs: 1
  ncd_cfg:
    metrics: [msp]
    tpr_th: 0.95
    prec_th: 0.3

algorithm:
  type: alice

criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ncdia/ncdia_remote_alice
