_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: cub200
    root: /new_data/czp/openhaiv/data/datasets/CIL/cub
    split: train
    subset_labels: 40
    # subset_file: /data/datasets/CIL/cub/cub/all/session_2.txt
    transform: train

valloader:
  dataset:
    _replace_: True
    type: cub200
    root: /new_data/czp/openhaiv/data/datasets/CIL/cub
    split: test
    subset_labels: 40
    transform: test

testloader:
  dataset:
    _replace_: True
    type: cub200
    root: /new_data/czp/openhaiv/data/datasets/CIL/cub
    split: test
    subset_labels: 40
    transform: test