_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: cub200
    root: /new_data/czp/openhaiv/data/datasets/CIL/cub
    split: train
    subset_labels: 160
    transform: train

valloader:
  dataset:
    _replace_: True
    type: cub200
    root: /new_data/czp/openhaiv/data/datasets/CIL/cub
    split: test
    subset_labels: 160
    transform: test

testloader:
  dataset:
    _replace_: True
    type: cub200
    root: /new_data/czp/openhaiv/data/datasets/CIL/cub
    split: test
    subset_labels: 160
    transform: test