dataloader:
  name: savc_att_dataloader
  dataset: remote
  base_class: '@{CIL.base_class}'
  num_classes: '@{CIL.num_classes}'
  att_classes: 86
  way: '@{CIL.way}'
  shot: '@{CIL.shot}'
  sessions: '@{CIL.sessions}'
  num_crops: '@{CIL.num_crops}'
  size_crops: '@{CIL.size_crops}'
  min_scale_crops: '@{CIL.min_scale_crops}'
  max_scale_crops: '@{CIL.max_scale_crops}'
  constrained_cropping: '@{CIL.constrained_cropping}'
  auto_augment: '@{CIL.auto_augment}'
  fantasy: '@{CIL.fantasy}'
  txt_path: D:\test\ATR-RGB\index
  att_path: D:\test\ATR-RGB\Attribute.xlsx
  split_file_train: D:\test\ATR-RGB\jpg_images\train
  split_file_test: D:\test\ATR-RGB\jpg_images\test  
  batch_size_base: 32
  batch_size_new: 64
  test_batch_size: 100
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'