_base_: [
  configs/dataloader/OES/oesfull.yaml,
  configs/algorithms/ood_detection/dml.yaml,
]

trainer:
  type: DetTrainer
  max_epochs: 50

algorithm:
  type: MSP

model:
  type: ResNet_Base
  network:
    type: ResNet50
    num_classes: 94
  checkpoint: your checkpoint here
  loss: CrossEntropyLoss
  
criterion:
  type: CrossEntropyLoss

optimizer:
  type: SGD
  lr: 0.01
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda
CIL: False
exp_name: exp
work_dir: ./output/ood/det_oes_rn50_mls
