_base_: [
  configs/dataloader/cifar10.yaml,
  configs/algorithms/ood_detection/dml.yaml,
]

trainer:
  type: DetTrainer
  max_epochs: 0

algorithm:
  type: VIM
  dim: 256


model:
  type: ResNet18
  num_classes: 10

criterion:
  type: CrossEntropyLoss

optimizer:
  type: Adam
  lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ood/det_cifar10_rn18_vim
