_base_: configs/dataloader/OES/oesfull.yaml
  
trainer:
  type: DetTrainer
  gather_train_stats: False
  gather_test_stats: False
  max_epochs: 0

algorithm:
  type: MLS

model:
  type: CustomCLIP_ZeroShot
  num_classes: 94
  backbone: 'ViT-B/16'
  local_path: "checkpoint/RS5M_ViT-B-32.pt"
  dataset: 'oes'
  text_prompt: 'simple'

criterion:
  type: CrossEntropyLoss


optimizer:
  type: sgd
  lr: 0.01
  weight_decay: 0.0005

scheduler:
  type: cosine_warmup
  T_max: 0
  warmup_epochs: 1
  warmup_type: constant
  warmup_lr: 1e-4


seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ood/det_oes_clip-rsb32_mls
