_base_: [
  configs/dataloader/OES/oesfull.yaml,
  configs/algorithms/ood_detection/dml.yaml,
]

trainer:
  type: DetTrainer
  max_epochs: 0

algorithm:
  type: MSP

model:
  type: ResNet_Base
  network:
    type: ResNet18
    num_classes: 94
  checkpoint: "/data/zqh/xz/openhaiv-ood_xz/output/ood/det_oes_rn18_mls_0401/exp/latest.pth"
  #/data/zqh/xz/openhaiv-ood_xz/output/ood/det_oes_rn18_mls/exp/latest.pth
  loss: CrossEntropyLoss
  
criterion:
  type: CrossEntropyLoss

optimizer:
  type: SGD
  lr: 0.01
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ood/det_oes_rn18_mls_0401
