_base_: configs/dataloader/OES/oesfull.yaml

trainer:
  type: DetTrainer
  gather_train_stats: False
  gather_test_stats: False
  max_epochs: 0
  load_from: './output/supervised/sl_oes_coop-rsb32/exp/latest.pth'


algorithm:
  type: MCM
  hyperparameters:
    T: 100

model:
  type: CoOp
  backbone: 'ViT-B/16'
  local_path: "checkpoint/RS5M_ViT-B-32.pt"
  dataset: 'oes'
  N_CTX: 16
  CTX_INIT: False
  image_size: 224
  CSC: True
  CLASS_TOKEN_POSITION: 'end'
  
criterion:
  type: CrossEntropyLoss

optimizer:
  type: sgd
  lr: 0.01
  # type: Adam
  # lr: 0.0003
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 1
device: cuda

exp_name: exp
work_dir: ./output/ood/det_oes_coop-rsb32_mcm
