_base_: [
  configs/dataloader/OES/oesfull.yaml,
  configs/algorithms/ood_detection/dml.yaml,
]

trainer:
  type: DetTrainer
  max_epochs: 50

algorithm:
  type: MSP

model:
  type: ResNet_Base
  network:
    type: ResNet18
    num_classes: 94
  checkpoint: your checkpoint here
  loss: LogitNormLoss
  
criterion:
  type: LogitNormLoss

optimizer:
  type: Adam
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  type: Constant

seed: 0
device: cuda

exp_name: exp
work_dir: ./output/ood/det_oes_rn18_mls_0401
