_base_: configs/dataloader/loader.yaml

trainloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/caltech101/caltech-101/
    split: train
    subset_file: /data/datasets/CIL/caltech101/caltech-101/session_1.txt
    transform: train

valloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/caltech101/caltech-101/
    split: test
    subset_labels: 101
    transform: test

testloader:
  dataset:
    _replace_: True
    type: remote
    root: /data/datasets/CIL/caltech101/caltech-101/
    split: test
    subset_labels: 101
    transform: test