_base_: [
  configs/dataloader/OES/oesfull.yaml,
  configs/algorithms/ood_detection/ood.yaml,
]

trainer:
  type: DetTrainer
  max_epochs: 0

algorithm:
  type: VOS
  
sample_number: 1000
feature_dim: 2048
sample_from: 10000
select: 1
loss_weight: 0.1
start_epoch: 0
model:
  type: ResNet_Base
  network:
    type: ResNet50
    num_classes: 94
  checkpoint: ./output/ood/det_oes_rn50_vos_lr0.01/exp/latest.pth
  loss: CrossEntropyLoss
  
criterion:
  type: CrossEntropyLoss

optimizer:
  type: SGD
  lr: 0.01
  weight_decay: 0.0001

scheduler:
  type: cosine
  T_max: 100  

seed: 0
device: cuda
CIL: False
exp_name: exp
work_dir: ./output/ood/test
